# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)
print(np.show_config())

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
import numpy as np
null_vector=np.zeros(10)
print(null_vector)
print(null_vector.size)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
10


#### 4. How to find the memory size of any array (★☆☆)

In [10]:
import numpy as np
null_vector=np.zeros(10)
print(null_vector.nbytes)



80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [11]:
import numpy as np
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [1]:
import numpy as np

null_vector = np.zeros(10)
null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
import numpy as np


my_vector = np.arange(10, 50)

print(my_vector)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [2]:
import numpy as np
my_vector = np.arange(10, 50)
reversed_vector = my_vector[::-1]

print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
import numpy as np
my_matrix = np.arange(9).reshape((3, 3))

print(my_matrix)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [3]:
import numpy as np
my_array = np.array([1, 2, 0, 0, 4, 0])
nonzero_indices = np.nonzero(my_array)

print(nonzero_indices)


(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [4]:
import numpy as np
identity_matrix = np.eye(3)

print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [5]:
import numpy as np
random_array = np.random.rand(3, 3, 3)

print(random_array)


[[[0.81992421 0.81474388 0.96480432]
  [0.29940392 0.0744745  0.25601773]
  [0.28059571 0.56633413 0.36283786]]

 [[0.58638344 0.91034433 0.55554617]
  [0.68857671 0.04472979 0.11560643]
  [0.12714093 0.09546659 0.06133691]]

 [[0.70621047 0.36238968 0.16935398]
  [0.8015414  0.81156806 0.95546605]
  [0.9819305  0.63593948 0.9070748 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
import numpy as np
random_array = np.random.rand(10, 10)
min_value = np.min(random_array)
max_value = np.max(random_array)

print("Array:")
print(random_array)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
import numpy as np
random_vector = np.random.rand(30)
mean_value = np.mean(random_vector)
print("Random Vector:")
print(random_vector)
print("\nMean value:", mean_value)


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [9]:
import numpy as np
my_array=np.zeros((4,7))
my_array[0,:]=1
my_array[-1,:]=1
my_array[:,0]=1
my_array[:,-1]=1
print(my_array)


[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [10]:
import numpy as np
existing_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])
new_shape = tuple(np.array(existing_array.shape) + 2)
new_array = np.zeros(new_shape, dtype=existing_array.dtype)
new_array[1:-1, 1:-1] = existing_array

print("Existing Array:")
print(existing_array)
print("\nArray with Border:")
print(new_array)


Existing Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array with Border:
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
nan
False
False
nan
True
True

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
import numpy as np

# Create a 5x5 matrix with values 1, 2, 3, 4 below the diagonal
diagonal_matrix = np.diag([1, 2, 3, 4], k=-1)

print(diagonal_matrix)


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
import numpy as np

# Create an 8x8 matrix with a checkerboard pattern
checkerboard_matrix = np.zeros((8, 8), dtype=int)

# Fill the checkerboard pattern with 1s
checkerboard_matrix[1::2, ::2] = 1  # Odd rows, even columns
checkerboard_matrix[::2, 1::2] = 1  # Even rows, odd columns

print(checkerboard_matrix)


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
import numpy as np

# Define the shape of the array
shape = (6, 7, 8)

# Find the index (x, y, z) of the 100th element
index = np.unravel_index(99, shape)

print("Index (x, y, z):", index)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
import numpy as np

# Create a 2x2 checkerboard pattern
checkerboard_tile = np.array([[0, 1], [1, 0]])

# Use tile to create an 8x8 checkerboard matrix
checkerboard_matrix = np.tile(checkerboard_tile, (4, 4))

print(checkerboard_matrix)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
import numpy as np

# Create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

# Normalize the matrix
normalized_matrix = (random_matrix - np.mean(random_matrix)) / np.std(random_matrix)

print("Original Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
import numpy as np

# Define a custom dtype for RGBA color
rgba_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])

# Create an array with the custom dtype
color_array = np.array([(255, 0, 0, 255),  # Red
                        (0, 255, 0, 255),  # Green
                        (0, 0, 255, 255)],  # Blue
                       dtype=rgba_dtype)

print(color_array)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
import numpy as np

# Create a 5x3 matrix
matrix_a = np.random.rand(5, 3)

# Create a 3x2 matrix
matrix_b = np.random.rand(3, 2)

# Multiply the matrices using np.dot
result_dot = np.dot(matrix_a, matrix_b)

# Multiply the matrices using @ operator (matrix multiplication)
result_at = matrix_a @ matrix_b

print("Matrix A (5x3):")
print(matrix_a)
print("\nMatrix B (3x2):")
print(matrix_b)
print("\nResult using np.dot (5x2):")
print(result_dot)
print("\nResult using @ operator (5x2):")
print(result_at)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
import numpy as np

# Create a 1D array
array_1d = np.array([1, 4, 6, 7, 3, 9, 2, 5, 8])

# Negate elements between 3 and 8 in place
array_1d[(array_1d > 3) & (array_1d < 8)] *= -1

print("Modified 1D Array:")
print(array_1d)


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
10
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [2]:
print("All expressions are legal except for the last one.")

All expressions are legal except for the last one.


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [4]:
nan
0
[nan]

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
import numpy as np

# Example float array
float_array = np.array([-1.5, -0.7, 0.7, 1.5])

# Round away from zero
rounded_array = np.round_(float_array, decimals=0, out=None, where=(float_array != 0), casting='same_kind', order='K', dtype=None)

print("Original array:", float_array)
print("Rounded away from zero:", rounded_array)


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
import numpy as np

# Example arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values
common_values = np.intersect1d(array1, array2)

print("Array 1:", array1)
print("Array 2:", array2)
print("Common values:", common_values)


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
import numpy as np
import warnings

# Suppress all NumPy warnings
warnings.filterwarnings("ignore", category=np.VisibleDeprecationWarning)

# Your code here

# Reset warnings to default behavior
warnings.resetwarnings()


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [5]:
import numpy as np

result_np_sqrt = np.sqrt(-1)
result_np_emath_sqrt = np.emath.sqrt(-1)

print("np.sqrt(-1):", result_np_sqrt)         # Output: 1j
print("np.emath.sqrt(-1):", result_np_emath_sqrt)  # Output: 1j
print(" So, Both expressions are true.")

np.sqrt(-1): nan
np.emath.sqrt(-1): 1j
 So, Both expressions are true.


<ipython-input-5-c83477f3e931>:3: RuntimeWarning: invalid value encountered in sqrt
  result_np_sqrt = np.sqrt(-1)


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [6]:
from datetime import datetime, timedelta

# Get today's date
today = datetime.now().date()

# Get yesterday's date
yesterday = today - timedelta(days=1)

# Get tomorrow's date
tomorrow = today + timedelta(days=1)

# Print the results
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2023-12-19
Today: 2023-12-20
Tomorrow: 2023-12-21


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [7]:
from datetime import datetime, timedelta

# Define the start date of July 2016
start_date = datetime(2016, 7, 1)

# Calculate the number of days in July 2016
days_in_month = 31  # July has 31 days

# Generate a list of dates for the entire month
date_list = [start_date + timedelta(days=i) for i in range(days_in_month)]

# Print the list of dates
for date in date_list:
    print(date)


2016-07-01 00:00:00
2016-07-02 00:00:00
2016-07-03 00:00:00
2016-07-04 00:00:00
2016-07-05 00:00:00
2016-07-06 00:00:00
2016-07-07 00:00:00
2016-07-08 00:00:00
2016-07-09 00:00:00
2016-07-10 00:00:00
2016-07-11 00:00:00
2016-07-12 00:00:00
2016-07-13 00:00:00
2016-07-14 00:00:00
2016-07-15 00:00:00
2016-07-16 00:00:00
2016-07-17 00:00:00
2016-07-18 00:00:00
2016-07-19 00:00:00
2016-07-20 00:00:00
2016-07-21 00:00:00
2016-07-22 00:00:00
2016-07-23 00:00:00
2016-07-24 00:00:00
2016-07-25 00:00:00
2016-07-26 00:00:00
2016-07-27 00:00:00
2016-07-28 00:00:00
2016-07-29 00:00:00
2016-07-30 00:00:00
2016-07-31 00:00:00


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
import numpy as np

# Assuming A and B are NumPy arrays
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Compute ((A+B)*(-A/2)) in place
A += B
A *= (-A/2)

# Print the result
print(A)


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [8]:
import numpy as np

# Generate a random array of positive numbers
random_array = np.random.rand(5) * 10  # Adjust the size as needed

# Method 1: Using astype(int)
integer_part_1 = random_array.astype(int)

print("Method 1:", integer_part_1)
# Method 2: Using floor function
integer_part_2 = np.floor(random_array)

print("Method 2:", integer_part_2)
# Method 3: Using trunc function
integer_part_3 = np.trunc(random_array)

print("Method 3:", integer_part_3)
# Method 4: Using map function with int
integer_part_4 = list(map(int, random_array))

print("Method 4:", integer_part_4)


Method 1: [4 5 4 2 1]
Method 2: [4. 5. 4. 2. 1.]
Method 3: [4. 5. 4. 2. 1.]
Method 4: [4, 5, 4, 2, 1]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
import numpy as np

# Create a 5x5 matrix with row values ranging from 0 to 4
matrix = np.tile(np.arange(5), (5, 1))

print(matrix)


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
import numpy as np

def generate_integers():
    for i in range(10):
        yield i

# Use the generator to build a NumPy array
generated_array = np.fromiter(generate_integers(), dtype=int)

print("Generated Array:", generated_array)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
import numpy as np

# Create a vector of size 10 with values ranging from 0 to 1 (exclusive)
vector = np.linspace(0, 1, 12, endpoint=False)[1:-1]

print("Generated Vector:", vector)


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Sort the vector
sorted_vector = np.sort(random_vector)

print("Random Vector:", random_vector)
print("Sorted Vector:", sorted_vector)


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
import numpy as np

# Create a small array
small_array = np.array([1, 2, 3, 4, 5])

# Using NumPy's np.sum
sum_np = np.sum(small_array)

# Using Python's built-in sum
sum_builtin = sum(small_array)

print("Sum using np.sum:", sum_np)
print("Sum using built-in sum:", sum_builtin)


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
import numpy as np

# Create two random arrays A and B
A = np.random.rand(5)
B = np.random.rand(5)

# Check if arrays A and B are equal
are_equal = np.array_equal(A, B)

print("Array A:", A)
print("Array B:", B)

if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
import numpy as np

# Create a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Make the array read-only
my_array.flags.writeable = False

# Try to modify the array (this will raise an error)
# Uncomment the following line to see the error
# my_array[0] = 10


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
import numpy as np

# Generate a random 10x2 matrix representing Cartesian coordinates
cartesian_coordinates = np.random.rand(10, 2)

# Extract x and y coordinates
x = cartesian_coordinates[:, 0]
y = cartesian_coordinates[:, 1]

# Convert to polar coordinates
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

# Display the results
print("Cartesian Coordinates:")
print(cartesian_coordinates)
print("\nPolar Coordinates:")
print("r:", r)
print("theta:", theta)


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
import numpy as np

# Generate a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random Vector:", random_vector)


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
import numpy as np

# Create a structured array with x and y coordinates
structured_array = np.zeros((10, 10), dtype=[('x', float), ('y', float)])

# Assign x and y coordinates
structured_array['x'], structured_array['y'] = np.meshgrid(np.linspace(0, 1, 10), np.linspace(0, 1, 10))

print(structured_array)


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
import numpy as np

# Example arrays X and Y
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# Construct the Cauchy matrix C
C = 1 / (X[:, np.newaxis] - Y)

print("Cauchy Matrix C:")
print(C)


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
import numpy as np

# Integer types
print("Integer Types:")
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f"{dtype}: Min = {info.min}, Max = {info.max}")

# Unsigned integer types
print("\nUnsigned Integer Types:")
for dtype in [np.uint8, np.uint16, np.uint32, np.uint64]:
    info = np.iinfo(dtype)
    print(f"{dtype}: Min = {info.min}, Max = {info.max}")

# Floating-point types
print("\nFloating-Point Types:")
for dtype in [np.float16, np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f"{dtype}: Min = {info.min}, Max = {info.max}")


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
import numpy as np

# Create a NumPy array
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Print all values using print()
print("Using print():")
print(my_array)

# Print all values directly in the Python interpreter
print("\nDirect output in the interpreter:")
my_array


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
import numpy as np

# Create a vector
vector = np.array([1, 3, 5, 7, 9, 11])

# Given scalar
given_scalar = 6

# Find the index of the closest value
closest_index = np.abs(vector - given_scalar).argmin()

# Get the closest value
closest_value = vector[closest_index]

print("Vector:", vector)
print("Given Scalar:", given_scalar)
print("Closest Value:", closest_value)


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)