### Questions 1

Create a matrix of 5x5 with random integers, after that swap its first and last rows.

In [85]:
import numpy as np
matrix=np.random.randint(1,100,size=(5,5))
print("Original Matrix:")
print(matrix)
temp_row=matrix[0].copy()
matrix[0]=matrix[-1]
matrix[-1]=temp_row

print("\nMatrix after swapping first and last rows:")
print(matrix)


Original Matrix:
[[36 12 81 41 85]
 [75  9 73 98 64]
 [70  6 85 31 86]
 [74 32 21 72 50]
 [84 24  6 23 12]]

Matrix after swapping first and last rows:
[[84 24  6 23 12]
 [75  9 73 98 64]
 [70  6 85 31 86]
 [74 32 21 72 50]
 [36 12 81 41 85]]


### Question 2

Create a 2D array, remove all rows that contain at least one zero.

In [76]:
import numpy as np
array_2d = np.random.randint(0,10,size=(5,4))
print("Original 2D Array:")
print(array_2d)
non_zero_rows = []
for row in array_2d:
    if not any(element==0 for element in row):
        non_zero_rows.append(row)
filtered_array_2d=np.array(non_zero_rows)
print("\nArray after removing rows with at least one zero:")
print(filtered_array_2d)


Original 2D Array:
[[3 8 4 0]
 [9 4 9 5]
 [3 5 6 6]
 [4 2 0 1]
 [2 2 2 5]]

Array after removing rows with at least one zero:
[[9 4 9 5]
 [3 5 6 6]
 [2 2 2 5]]


### Question 3

Write a NumPy program to find the real and imaginary parts of an array of complex numbers.<br>
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]

In [77]:
import numpy as np
original_array=np.array([1.00000000+0.j,0.70710678+0.70710678j])
real_parts=np.empty_like(original_array, dtype=float)
imaginary_parts=np.empty_like(original_array, dtype=float)
for i in range(len(original_array)):
    real_parts[i]=original_array[i].real
    imaginary_parts[i]=original_array[i].imag
print("Original Array:")
print(original_array)
print("\nReal Parts:")
print(real_parts)
print("\nImaginary Parts:")
print(imaginary_parts)


Original Array:
[1.        +0.j         0.70710678+0.70710678j]

Real Parts:
[1.         0.70710678]

Imaginary Parts:
[0.         0.70710678]


### Question 4

Write a NumPy program to remove the duplicate elements of an array.<br>
Original array:
[10 10 20 20 30 30]


In [73]:
import numpy as np

a=np.array([10,10,20,20,30,30])
b=np.empty(0,dtype=a.dtype)
for i in a:
    if i not in b:
        b = np.append(b,i)
print("Original Array:")
print(a)
print("\nArray after removing duplicates:")
print(b)


Original Array:
[10 10 20 20 30 30]

Array after removing duplicates:
[10 20 30]


### Question 5

Write a NumPy program to create a 3x3x3 array with random values.

In [30]:
a=np.random.rand(3,3,3)
a

array([[[0.6487286 , 0.97007932, 0.251313  ],
        [0.75566317, 0.86993602, 0.27850941],
        [0.34369654, 0.52385035, 0.06071459]],

       [[0.95454726, 0.65876326, 0.26476452],
        [0.5274488 , 0.67928055, 0.1231716 ],
        [0.74738271, 0.41917714, 0.55578136]],

       [[0.8019725 , 0.12117906, 0.10913874],
        [0.63638583, 0.05111479, 0.41548288],
        [0.90235253, 0.62044356, 0.24627728]]])

### Question 6

Write a NumPy program to create a random vector of size 10 and sort it.
<b>Note:<\b> Do not use builtin sorting function

In [46]:
random_vector=np.random.randint(1,50,size=(10))
print(random_vector)
for i in range(len(random_vector)):
    for j in range(0,len(random_vector)-i-1):
        if random_vector[j]>random_vector[j+1]:
            random_vector[j],random_vector[j+1]=random_vector[j+1],random_vector[j]
print(random_vector)               

[33 13 33 20 20 12 27 37  3 20]
[ 3 12 13 20 20 20 27 33 33 37]


### Question 7

Write a NumPy program to check two random arrays are equal or not.

In [78]:
import numpy as np
array1 = np.random.randint(1, 10, size=(5,))
array2 = np.random.randint(1, 10, size=(5,))
are_equal = True
if array1.shape == array2.shape:
    for i in range(len(array1)):
        if array1[i] != array2[i]:
            are_equal = False
            break
else:
    are_equal = False
print("Array 1:", array1)
print("Array 2:", array2)
if are_equal:
    print("The arrays are equal.")
else:
    print("The arrays are not equal.")


Array 1: [3 1 2 1 8]
Array 2: [4 5 5 5 2]
The arrays are not equal.


### Question 8 

Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.<br>

Original array:<br>
[[10 40]<br>
[30 20]]

In [67]:
import numpy as np
original_array = np.array([[10, 40], [30, 20]])
sorted_array_axis0 = np.sort(original_array, axis=0)
sorted_array_last_axis = np.sort(original_array, axis=-1)
sorted_flattened_array = np.sort(original_array.flatten())
print("Original Array:")
print(original_array)
print("\nSorted along the first axis (axis=0):")
print(sorted_array_axis0)
print("\nSorted along the last axis (axis=-1):")
print(sorted_array_last_axis)
print("\nSorted flattened array:")
print(sorted_flattened_array)


Original Array:
[[10 40]
 [30 20]]

Sorted along the first axis (axis=0):
[[10 20]
 [30 40]]

Sorted along the last axis (axis=-1):
[[10 40]
 [20 30]]

Sorted flattened array:
[10 20 30 40]


### Question 9

Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.<br>

Original array:<br>
[-1.6 -1.5 -0.3 0.1 1.4 1.8 2. ]

In [86]:
import numpy as np
original_array=np.array([-1.6,-1.5,-0.3,0.1,1.4,1.8,2.])
floor_values=np.floor(original_array)
ceiling_values=np.ceil(original_array)
truncated_values=np.trunc(original_array)
print("Original Array:")
print(original_array)
print("\nFloor Values:")
print(floor_values)
print("\nCeiling Values:")
print(ceiling_values)
print("\nTruncated Values:")
print(truncated_values)


Original Array:
[-1.6 -1.5 -0.3  0.1  1.4  1.8  2. ]

Floor Values:
[-2. -2. -1.  0.  1.  1.  2.]

Ceiling Values:
[-1. -1. -0.  1.  2.  2.  2.]

Truncated Values:
[-1. -1. -0.  0.  1.  1.  2.]


### Questions 10

Write a NumPy program to display all the dates for the month of March, 2017

In [83]:
import numpy as np
from datetime import datetime, timedelta
start_date=datetime(2017, 3, 1)
end_date=datetime(2017, 3, 31)
dates_array=np.arange(start_date,end_date+timedelta(days=1),timedelta(days=1))
print("Dates for the month of March, 2017:")
for date in dates_array:
    print(date)


Dates for the month of March, 2017:
2017-03-01T00:00:00.000000
2017-03-02T00:00:00.000000
2017-03-03T00:00:00.000000
2017-03-04T00:00:00.000000
2017-03-05T00:00:00.000000
2017-03-06T00:00:00.000000
2017-03-07T00:00:00.000000
2017-03-08T00:00:00.000000
2017-03-09T00:00:00.000000
2017-03-10T00:00:00.000000
2017-03-11T00:00:00.000000
2017-03-12T00:00:00.000000
2017-03-13T00:00:00.000000
2017-03-14T00:00:00.000000
2017-03-15T00:00:00.000000
2017-03-16T00:00:00.000000
2017-03-17T00:00:00.000000
2017-03-18T00:00:00.000000
2017-03-19T00:00:00.000000
2017-03-20T00:00:00.000000
2017-03-21T00:00:00.000000
2017-03-22T00:00:00.000000
2017-03-23T00:00:00.000000
2017-03-24T00:00:00.000000
2017-03-25T00:00:00.000000
2017-03-26T00:00:00.000000
2017-03-27T00:00:00.000000
2017-03-28T00:00:00.000000
2017-03-29T00:00:00.000000
2017-03-30T00:00:00.000000
2017-03-31T00:00:00.000000


### Question 11

Write a NumPy program to create 24 python datetime.datetime objects (single object for every hour), and then put it in a numpy array.

In [60]:
import numpy as np
from datetime import datetime, timedelta
start_time=datetime.now().replace(minute=0,second=0,microsecond=0)
datetime_objects=np.array([start_time+timedelta(hours=i) for i in range(24)])
print("Datetime Objects Array:")
print(datetime_objects)


Datetime Objects Array:
[datetime.datetime(2023, 12, 21, 13, 0)
 datetime.datetime(2023, 12, 21, 14, 0)
 datetime.datetime(2023, 12, 21, 15, 0)
 datetime.datetime(2023, 12, 21, 16, 0)
 datetime.datetime(2023, 12, 21, 17, 0)
 datetime.datetime(2023, 12, 21, 18, 0)
 datetime.datetime(2023, 12, 21, 19, 0)
 datetime.datetime(2023, 12, 21, 20, 0)
 datetime.datetime(2023, 12, 21, 21, 0)
 datetime.datetime(2023, 12, 21, 22, 0)
 datetime.datetime(2023, 12, 21, 23, 0)
 datetime.datetime(2023, 12, 22, 0, 0)
 datetime.datetime(2023, 12, 22, 1, 0)
 datetime.datetime(2023, 12, 22, 2, 0)
 datetime.datetime(2023, 12, 22, 3, 0)
 datetime.datetime(2023, 12, 22, 4, 0)
 datetime.datetime(2023, 12, 22, 5, 0)
 datetime.datetime(2023, 12, 22, 6, 0)
 datetime.datetime(2023, 12, 22, 7, 0)
 datetime.datetime(2023, 12, 22, 8, 0)
 datetime.datetime(2023, 12, 22, 9, 0)
 datetime.datetime(2023, 12, 22, 10, 0)
 datetime.datetime(2023, 12, 22, 11, 0)
 datetime.datetime(2023, 12, 22, 12, 0)]


### Question 12

Write a NumPy program to concatenate element-wise two arrays of string.<br>
<b>Example <\b>
Array1:<br>
['Python' 'PHP']<br>
Array2:<br>
[' Java' ' C++']<br>
new array:<br>
['Python Java' 'PHP C++']<br>

In [90]:
def Con(a1,a2):
    if len(a1)!=len(a1):
        print("Array is not of same size")
    else:
        arr_s=[a+b for a, b in zip(a1,a2)]
    return arr_s
a1=np.array(['Python','PHP'],dtype='str')
a2=np.array(['Java','C++'],dtype='str')
result=Con(s1,s2)
result


['Pythonjava', 'PHPc++']